name 'redis'
maintainer 'Joe Gardiner'
maintainer_email 'joe@joegardiner.co.uk'
license 'all_rights'
description 'Installs/Configures redis'
long_description 'Installs/Configures redis'
version '0.1.3'

depends 'apt', '~> 2.6.1'
depends 'firewall', '~> 2.0.0'
